### ISSUE TITLE
A file is missing

### ISSUE THREAD

**Issue by YongzhengCui** [dmartinezbaselga/intrinsic-rewards-navigation#1]
Thank you so much for your excellent work. When I execute the command, the following error occurs, it seems that a file is missing:

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from crowd_nav.policy.policy_factory import policy_factory
  File "/home/ros/cbl/intrinsic-rewards-navigation/crowd_nav/policy/policy_factory.py", line 2, in <module>
    from crowd_nav.policy.cadrl import CADRL
ModuleNotFoundError: No module named 'crowd_nav.policy.cadrl'

**Comment by dmartinezbaselga** [comment]
Thank you for bringing the issue to my attention, I apologize for the inconvenience. The error is fixed. Please let me know if you have any further issues or questions.
