### ISSUE TITLE
Run policy for one episode and visualize the result.

### ISSUE THREAD

**Issue by Lilyoung2000** [dmartinezbaselga/intrinsic-rewards-navigation#2]
![default](https://github.com/dmartinezbaselga/intrinsic-rewards-navigation/assets/97268825/f3b15b15-76e9-42aa-b47f-b73d9c6ac08c)

When I perform visualization, the terminal outputs warnings and returns several sets of status information. How can I solve this problem?

**Comment by aleflabo** [comment]
I've the same error too. Did you manage to solve the issue?

**Comment by aleflabo** [comment]
I solved it commenting the 
`exit()`  
line in test.py

**Comment by Lilyoung2000** [comment]
Awesome, thank you. Which line should be added specifically? Do you have any ideas about integrating re3 and icm classes into other projects?

**Comment by Lilyoung2000** [comment]
Sorry, I misunderstood, it works now

**Comment by dmartinezbaselga** [comment]
Thanks for your comments! I think it was there due to some debugging... It's not there anymore
