### ISSUE TITLE
Doubt about the steering angles

### ISSUE THREAD

**Issue by aleflabo** [dmartinezbaselga/intrinsic-rewards-navigation#3]
Dear authors,

Working at your code (by the way, thank you for making it open source!), I've noticed that there could be an incongruence with what is written in the paper. 
In the paper, in the "Problem Formulation" section, the steering angles are 16 evenly spaced in 0 and 2π radians.

In the code, there seems to be a limitation on the values of the rotations. By default is set to $[- \pi / 6, - \pi / 6]$, which is a hard constraint. 

Am I missing something?

Thanks for any help you can provide.

Alessandro

**Comment by dmartinezbaselga** [comment]
Hi! Thank you for your comment. You are right. I can't tell you if it's a typo in the paper or something I changed in the code, as I conducted some other experiments different from those in the paper, also in a UGV. Anyway, you can adapt it to your robot constraints ;). You can contact me if you need any help!
